-- 1. Enable extensions
create extension if not exists "uuid-ossp";

-- 2. Create Tables
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  username text,
  avatar_url text,
  updated_at timestamp with time zone
);

create table brands (
  id bigint generated by default as identity primary key,
  name text not null,
  logo_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table categories (
  id bigint generated by default as identity primary key,
  name text not null,
  parent_id bigint references categories(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table products (
  id uuid default uuid_generate_v4() primary key,
  title text not null,
  description text,
  price integer not null,
  images text[] not null default '{}',
  brand_id bigint references brands(id),
  category_id bigint references categories(id),
  year integer,
  status text check (status in ('available', 'reserved', 'sold')) default 'available',
  user_id uuid references profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable RLS
alter table profiles enable row level security;
alter table products enable row level security;
alter table brands enable row level security;
alter table categories enable row level security;

-- 4. Policies
-- Public read access
create policy "Public products are viewable by everyone" on products for select using (true);
create policy "Public brands are viewable by everyone" on brands for select using (true);
create policy "Public categories are viewable by everyone" on categories for select using (true);
create policy "Public profiles are viewable by everyone" on profiles for select using (true);

-- Authenticated users access
create policy "Users can insert their own products" on products for insert with check (auth.uid() = user_id);
create policy "Users can update their own products" on products for update using (auth.uid() = user_id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- 5. Helper Function & Trigger for User Creation
-- This automatically creates a profile entry when a new user signs up (via Google or Email)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (
    new.id,
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'avatar_url'
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 6. Seed Data (Optional)
insert into brands (name) values ('Hyundai'), ('Kia'), ('BMW'), ('Mercedes-Benz'), ('Audi');
insert into categories (name) values ('Engine'), ('Transmission'), ('Suspension'), ('Brake'), ('Interior'), ('Exterior'), ('Electronics');
